<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>


# My Jupyter Notebook on IBM Watson Studio

**Ihar Laurenau**

Electronics engineer

*The science of data is close to me for several reasons: I have always been interested in mathematics, statistics, patterns, numbers, and it seems to me that our whole world is built on binary logic.*

### My code calculates the matrix product of two matrices of different dimensions. (R)

In [9]:
F = matrix(c(1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1), nrow = 3, ncol = 4)
Ft = matrix(c(1, 1, 1, 1, 1, -1, 1, -1, 1, 1, -1, -1), nrow = 4, ncol = 3)
num_of_rows = nrow(F)
num_of_cols = ncol(Ft)
div = matrix(, nrow = num_of_rows, ncol = num_of_cols)
print(F)
print(Ft)
for(row in 1:num_of_rows) 
{
    for(col in 1:num_of_cols) 
    {
        div[row, col] <- F[row, col] / Ft[row, col]
    }
}
print(div)

     [,1] [,2] [,3] [,4]
[1,]    1    1    1    1
[2,]    1    1   -1   -1
[3,]    1   -1    1   -1
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1   -1    1
[3,]    1    1   -1
[4,]    1   -1   -1
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1   -1   -1
[3,]    1   -1   -1


*Bulleted list*
-  one
-  two
-  three

*Numbered list*

<ol>
    <li>One</li>
    <li>Two</li>
    <li>Three</li>
</ol>

*Hyperlink*

<<a href="https://data platform.cloud.ibm.com/gallery ">IBM Cloud Gallery</a>

*Table*

| Header 1 | Header 2 | Header 3 |
| ------ | ------ | ------ |
| Cell 1 | Cell 2 | Cell 3 |